### ISSUE TITLE
你好，可以提供另外两个数据集的下载链接吗？

### ISSUE THREAD

**Issue by limycml** [WendellGul/DCMH#1]
感谢你提供DCMH的PYTORCH代码，你提供了FLICKR-25K.mat的下载链接，非常感谢，请问可否提供另外两个数据集（IAPR TC-12、NUS-WIDE）的下载链接？或者合并文件的方法?
还有导入和预处理另两个数据集的代码方便提供吗？

**Comment by WendellGul** [comment]
这里给出的.mat数据文件的分享链接都是论文原作者给出的，具体可以参见论文原作者的Github项目关于数据下载链接的[说明](https://github.com/jiangqy/DCMH-CVPR2017/blob/master/DCMH_tensorflow/DCMH_tensorflow/readme.txt)。
因为直接使用的原作者处理的数据，没有实现数据处理的部分，抱歉无法提供。
