### ISSUE TITLE
您好，请问您可以复现论文结果吗？我的mAP值很低，想请您帮我看看。

### ISSUE THREAD

**Issue by zhanjw** [WendellGul/DCMH#2]
您好，非常感谢您的pytorch实现。
我使用了您的代码并进行了一定的修改，使其能够通过Dataloader按需加载数据，而不是一次装载进内存。
我想请问一下您可以复现原论文的结果吗（Flickr25k数据集）？大概需要迭代多少次？
因为我无法复现论文的结果，我想知道是不是作者的问题亦或者是我自己修改时导致的问题？
在训练过程中，loss函数的term1和term2基本保持不变，仅term3能显著降低。但是最后的mAP值并没有取得效果。
logloss(term1) tensor(69321232., device='cuda:0')
quantization(term2) tensor(301857.3125, device='cuda:0')
balance(term3) tensor(924399.3750, device='cuda:0')
经过500次epoch之后，检索测试的mAP值基本与随机模型直接进行检索测试的mAP值一致，为55%，相当于没有学习到有用的信息。
我不知道应该是哪里出了问题，想请您帮我看看。最有可能出问题的地方应该在哪里？

**Comment by WendellGul** [comment]
您好，我在Flickr25K上复现的结果是(64bit)：MAP(I->T)=0.7418, MAP(T->I)=0.7730，和原文相差不多，训练了300个epoch。
如果您检查过发现修改没问题的话，可以试一下换一种优化器（如Adam或Adamax），或者调低一点学习率（如0.001），再看看训练的结果。

**Comment by SCNU-WH** [comment]
> 您好，我在Flickr25K上复现的结果是(64bit)：MAP(I->T)=0.7418, MAP(T->I)=0.7730，和原文相差不多，训练了300个epoch。 如果您检查过发现修改没问题的话，可以试一下换一种优化器（如Adam或Adamax），或者调低一点学习率（如0.001），再看看训练的结果。

您好，请问这个是验证的MAP吗，我valid的MAP也有这么高valid MAP: MAP(i->t): 0.7383, MAP(t->i): 0.7714，但是test MAP: MAP(i->t): 0.708, MAP(t->i): 0.743
要低3个点，也是训练了300个epoch。
感谢！

**Comment by Senmo996** [comment]
> 您好，非常感谢您的pytorch实现。 我使用了您的代码并进行了一定的修改，使其能够通过Dataloader按需加载数据，而不是一次装载进内存。 我想请问一下您可以复现原论文的结果吗（Flickr25k数据集）？大概需要迭代多少次？ 因为我无法复现论文的结果，我想知道是不是作者的问题亦或者是我自己修改时导致的问题？ 在训练过程中，loss函数的term1和term2基本保持不变，仅term3能显著降低。但是最后的mAP值并没有取得效果。 logloss(term1) tensor(69321232., device='cuda:0') quantization(term2) tensor(301857.3125, device='cuda:0') balance(term3) tensor(924399.3750, device='cuda:0') 经过500次epoch之后，检索测试的mAP值基本与随机模型直接进行检索测试的mAP值一致，为55%，相当于没有学习到有用的信息。 我不知道应该是哪里出了问题，想请您帮我看看。最有可能出问题的地方应该在哪里？

您好，我也是通过Dataloader按需加载数据，也出现了和您一样的问题，请问您后来解决了吗？
