### ISSUE TITLE
Requesting pretrained vgg-net model. 

### ISSUE THREAD

**Issue by prraoo** [WendellGul/DCMH#3]
Hello, @WendellGul thanks for the code. 

I am trying to use your code, unfortunately, I am unable to download the pre-trained model from the Baidu server. 

I tried using "imagenet-vgg-f.mat" fromhttp://www.vlfeat.org/matconvnet/pretrained/ but I am getting the following error:
`File "/home/codes/DCMH_pytorch/models/img_module.py", line 63, in _init
    self.mean = torch.from_numpy(data['normalization'][0][0][0].transpose()).type(torch.float)
KeyError: 'normalization'
`
Is there any other way you can share the pre-trained model?

**Comment by WendellGul** [comment]
Perhaps you can download the pre-trained model here:  https://www.dropbox.com/s/1g5brlygdw9us0a/imagenet-vgg-f.mat?dl=0

**Comment by prraoo** [comment]
Thank you
